
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
/// <summary>
/// 数值计算器 基类
/// </summary>
public abstract partial class BaseCalculator : Luban.BeanBase
{
    public BaseCalculator(ByteBuf _buf) 
    {
    }

    public static BaseCalculator DeserializeBaseCalculator(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case battle.FloatCalculator.__ID__: return new battle.FloatCalculator(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

