
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
/// <summary>
/// 伤害计算器
/// </summary>
public sealed partial class DamageCalculator : BaseCalculator
{
    public DamageCalculator(ByteBuf _buf)  : base(_buf) 
    {
        Value = global::cfg.battle.DynamicValue.DeserializeDynamicValue(_buf);
        Type = (battle.EDamageType)_buf.ReadInt();
    }

    public static DamageCalculator DeserializeDamageCalculator(ByteBuf _buf)
    {
        return new battle.DamageCalculator(_buf);
    }

    /// <summary>
    /// 数值，需要指定
    /// </summary>
    public readonly battle.DynamicValue Value;
    /// <summary>
    /// 伤害类型，需要指定
    /// </summary>
    public readonly battle.EDamageType Type;
   
    public const int __ID__ = 1709306471;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Value?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "value:" + Value + ","
        + "type:" + Type + ","
        + "}";
    }
}
}

