
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
/// <summary>
/// 动态数值 = 基础数值 + 单位动态属性值(如果指定)
/// </summary>
public sealed partial class DynamicValue : Luban.BeanBase
{
    public DynamicValue(ByteBuf _buf) 
    {
        BaseValue = _buf.ReadFloat();
        DynamicAttr = (battle.ESkillAttr)_buf.ReadInt();
    }

    public static DynamicValue DeserializeDynamicValue(ByteBuf _buf)
    {
        return new battle.DynamicValue(_buf);
    }

    /// <summary>
    /// 基础数值，需要指定
    /// </summary>
    public readonly float BaseValue;
    /// <summary>
    /// 技能属性，默认为 无
    /// </summary>
    public readonly battle.ESkillAttr DynamicAttr;
   
    public const int __ID__ = 102410760;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "baseValue:" + BaseValue + ","
        + "dynamicAttr:" + DynamicAttr + ","
        + "}";
    }
}
}

