
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.battle
{ 
    /// <summary>
    /// 伤害类型
    /// </summary>
    [System.Flags]
    public enum EDamageType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 直伤
        /// </summary>
        Direct = 1,
        /// <summary>
        /// DOT
        /// </summary>
        Dot = 2,
    }

} 

