
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.battle
{ 
    /// <summary>
    /// 持续时间类型
    /// </summary>
    public enum EDurationType
    {
        /// <summary>
        /// 即时
        /// </summary>
        None = 0,
        /// <summary>
        /// 持续
        /// </summary>
        Duration = 1,
        /// <summary>
        /// 永久
        /// </summary>
        Infinite = 2,
    }

} 

