
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.battle
{ 
    /// <summary>
    /// 肉鸽磁条的品质等级
    /// </summary>
    public enum EGameRougeEffectQuality
    {
        /// <summary>
        /// 白
        /// </summary>
        Quality1 = 0,
        /// <summary>
        /// 绿
        /// </summary>
        Quality2 = 1,
        /// <summary>
        /// 蓝
        /// </summary>
        Quality3 = 2,
        /// <summary>
        /// 紫
        /// </summary>
        Quality4 = 3,
        /// <summary>
        /// 橙
        /// </summary>
        Quality5 = 4,
        /// <summary>
        /// 红
        /// </summary>
        Quality6 = 5,
    }

} 

