
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.battle
{ 
    /// <summary>
    /// 游戏标签
    /// </summary>
    public enum EGameTag
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 霸体
        /// </summary>
        Armor = 1,
        /// <summary>
        /// 无敌
        /// </summary>
        Invincible = 2,
        /// <summary>
        /// 异常状态
        /// </summary>
        AbnormalState = 3,
        /// <summary>
        /// 冰冻
        /// </summary>
        Freeze = 4,
        /// <summary>
        /// 眩晕
        /// </summary>
        Stun = 5,
        Max = 6,
    }

} 

