
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.battle
{ 
    public enum EGameAttr
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 最大血量
        /// </summary>
        MaxHp = 1,
        /// <summary>
        /// 最大血量Base
        /// </summary>
        MaxHpBase = 2,
        /// <summary>
        /// 最大血量Mult
        /// </summary>
        MaxHpMult = 3,
        /// <summary>
        /// 最大血量Add
        /// </summary>
        MaxHpAdd = 4,
        /// <summary>
        /// 攻击力
        /// </summary>
        Atk = 5,
        /// <summary>
        /// 攻击力Base
        /// </summary>
        AtkBase = 6,
        /// <summary>
        /// 攻击力Mult
        /// </summary>
        AtkMult = 7,
        /// <summary>
        /// 攻击力Add
        /// </summary>
        AtkAdd = 8,
        /// <summary>
        /// 暴击率
        /// </summary>
        CriticalRate = 9,
        /// <summary>
        /// 暴击率Base
        /// </summary>
        CriticalRateBase = 10,
        /// <summary>
        /// 暴击率Mult
        /// </summary>
        CriticalRateMult = 11,
        /// <summary>
        /// 暴击率Add
        /// </summary>
        CriticalRateAdd = 12,
        /// <summary>
        /// 暴击倍率
        /// </summary>
        CriticalRatio = 13,
        /// <summary>
        /// 暴击倍率Base
        /// </summary>
        CriticalRatioBase = 14,
        /// <summary>
        /// 暴击倍率Mult
        /// </summary>
        CriticalRatioMult = 15,
        /// <summary>
        /// 暴击倍率Add
        /// </summary>
        CriticalRatioAdd = 16,
        /// <summary>
        /// 总增伤
        /// </summary>
        DamageMore = 17,
        /// <summary>
        /// 总增Base
        /// </summary>
        DamageMoreBase = 18,
        /// <summary>
        /// 总增Mult
        /// </summary>
        DamageMoreMult = 19,
        /// <summary>
        /// 总增Add
        /// </summary>
        DamageMoreAdd = 20,
        /// <summary>
        /// 总减伤
        /// </summary>
        DamageLess = 21,
        /// <summary>
        /// 总减伤Base
        /// </summary>
        DamageLessBase = 22,
        /// <summary>
        /// 总减伤Mult
        /// </summary>
        DamageLessMult = 23,
        /// <summary>
        /// 总减伤Add
        /// </summary>
        DamageLessAdd = 24,
        /// <summary>
        /// 充能
        /// </summary>
        SpecialCharge = 25,
        /// <summary>
        /// 充能Base
        /// </summary>
        SpecialChargeBase = 26,
        /// <summary>
        /// 充能Mult
        /// </summary>
        SpecialChargeMult = 27,
        /// <summary>
        /// 充能Add
        /// </summary>
        SpecialChargeAdd = 28,
        /// <summary>
        /// 当前血量
        /// </summary>
        CurHp = 29,
        /// <summary>
        /// 当前能量
        /// </summary>
        CurSpecialEnergy = 30,
        Max = 31,
        /// <summary>
        /// Meta伤害
        /// </summary>
        MetaDamage = 32,
        /// <summary>
        /// Meta修改技能属性
        /// </summary>
        MetaChangeSkillAttr = 33,
    }

} 

