
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.battle
{ 
    public enum EGameAttr
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 最大血量
        /// </summary>
        MaxHp = 1,
        /// <summary>
        /// 最大血量Base
        /// </summary>
        MaxHpBase = 2,
        /// <summary>
        /// 最大血量Mult
        /// </summary>
        MaxHpMult = 3,
        /// <summary>
        /// 最大血量Add
        /// </summary>
        MaxHpAdd = 4,
        /// <summary>
        /// 攻击力
        /// </summary>
        Atk = 5,
        /// <summary>
        /// 攻击力Base
        /// </summary>
        AtkBase = 6,
        /// <summary>
        /// 攻击力Mult
        /// </summary>
        AtkMult = 7,
        /// <summary>
        /// 攻击力Add
        /// </summary>
        AtkAdd = 8,
        /// <summary>
        /// 防御力
        /// </summary>
        Defence = 9,
        /// <summary>
        /// 防御力Base
        /// </summary>
        DefenceBase = 10,
        /// <summary>
        /// 防御力Mult
        /// </summary>
        DefenceMult = 11,
        /// <summary>
        /// 防御力Add
        /// </summary>
        DefenceAdd = 12,
        /// <summary>
        /// 固定防御穿透
        /// </summary>
        DefenceFixedIgnore = 13,
        /// <summary>
        /// 固定防御穿透Base
        /// </summary>
        DefenceFixedIgnoreBase = 14,
        /// <summary>
        /// 固定防御穿透Mult
        /// </summary>
        DefenceFixedIgnoreMult = 15,
        /// <summary>
        /// 固定防御穿透Add
        /// </summary>
        DefenceFixedIgnoreAdd = 16,
        /// <summary>
        /// 百分比防御穿透
        /// </summary>
        DefencePctIgnore = 17,
        /// <summary>
        /// 百分比防御穿透Base
        /// </summary>
        DefencePctIgnoreBase = 18,
        /// <summary>
        /// 百分比防御穿透Mult
        /// </summary>
        DefencePctIgnoreMult = 19,
        /// <summary>
        /// 百分比防御穿透Add
        /// </summary>
        DefencePctIgnoreAdd = 20,
        /// <summary>
        /// 暴击率
        /// </summary>
        CriticalRate = 21,
        /// <summary>
        /// 暴击率Base
        /// </summary>
        CriticalRateBase = 22,
        /// <summary>
        /// 暴击率Mult
        /// </summary>
        CriticalRateMult = 23,
        /// <summary>
        /// 暴击率Add
        /// </summary>
        CriticalRateAdd = 24,
        /// <summary>
        /// 抗暴击率
        /// </summary>
        DeCriticalRate = 25,
        /// <summary>
        /// 抗暴击率Base
        /// </summary>
        DeCriticalRateBase = 26,
        /// <summary>
        /// 抗暴击率Mult
        /// </summary>
        DeCriticalRateMult = 27,
        /// <summary>
        /// 抗暴击率Add
        /// </summary>
        DeCriticalRateAdd = 28,
        /// <summary>
        /// 暴击倍率
        /// </summary>
        CriticalRatio = 29,
        /// <summary>
        /// 暴击倍率Base
        /// </summary>
        CriticalRatioBase = 30,
        /// <summary>
        /// 暴击倍率Mult
        /// </summary>
        CriticalRatioMult = 31,
        /// <summary>
        /// 暴击倍率Add
        /// </summary>
        CriticalRatioAdd = 32,
        /// <summary>
        /// 抗暴击倍率
        /// </summary>
        DeCriticalRatio = 33,
        /// <summary>
        /// 抗暴击倍率Base
        /// </summary>
        DeCriticalRatioBase = 34,
        /// <summary>
        /// 抗暴击倍率Mult
        /// </summary>
        DeCriticalRatioMult = 35,
        /// <summary>
        /// 抗暴击倍率Add
        /// </summary>
        DeCriticalRatioAdd = 36,
        /// <summary>
        /// 总增伤
        /// </summary>
        DamageMore = 37,
        /// <summary>
        /// 总增Base
        /// </summary>
        DamageMoreBase = 38,
        /// <summary>
        /// 总增Mult
        /// </summary>
        DamageMoreMult = 39,
        /// <summary>
        /// 总增Add
        /// </summary>
        DamageMoreAdd = 40,
        /// <summary>
        /// 总减伤
        /// </summary>
        DamageLess = 41,
        /// <summary>
        /// 总减伤Base
        /// </summary>
        DamageLessBase = 42,
        /// <summary>
        /// 总减伤Mult
        /// </summary>
        DamageLessMult = 43,
        /// <summary>
        /// 总减伤Add
        /// </summary>
        DamageLessAdd = 44,
        /// <summary>
        /// 技能极速
        /// </summary>
        SkillHaste = 45,
        /// <summary>
        /// 技能极速Base
        /// </summary>
        SkillHasteBase = 46,
        /// <summary>
        /// 技能极速Mult
        /// </summary>
        SkillHasteMult = 47,
        /// <summary>
        /// 技能极速Add
        /// </summary>
        SkillHasteAdd = 48,
        /// <summary>
        /// 行动充能
        /// </summary>
        ActionCharge = 49,
        /// <summary>
        /// 行动充能Base
        /// </summary>
        ActionChargeBase = 50,
        /// <summary>
        /// 行动充能Mult
        /// </summary>
        ActionChargeMult = 51,
        /// <summary>
        /// 行动充能Add
        /// </summary>
        ActionChargeAdd = 52,
        /// <summary>
        /// 动态属性01
        /// </summary>
        DynamicAttr01 = 53,
        /// <summary>
        /// 动态属性02
        /// </summary>
        DynamicAttr02 = 54,
        /// <summary>
        /// 动态属性03
        /// </summary>
        DynamicAttr03 = 55,
        /// <summary>
        /// 动态属性04
        /// </summary>
        DynamicAttr04 = 56,
        /// <summary>
        /// 动态属性05
        /// </summary>
        DynamicAttr05 = 57,
        /// <summary>
        /// 动态属性06
        /// </summary>
        DynamicAttr06 = 58,
        /// <summary>
        /// 动态属性07
        /// </summary>
        DynamicAttr07 = 59,
        /// <summary>
        /// 动态属性08
        /// </summary>
        DynamicAttr08 = 60,
        /// <summary>
        /// 动态属性09
        /// </summary>
        DynamicAttr09 = 61,
        /// <summary>
        /// 动态属性10
        /// </summary>
        DynamicAttr10 = 62,
        /// <summary>
        /// 动态属性11
        /// </summary>
        DynamicAttr11 = 63,
        /// <summary>
        /// 动态属性12
        /// </summary>
        DynamicAttr12 = 64,
        /// <summary>
        /// 动态属性13
        /// </summary>
        DynamicAttr13 = 65,
        /// <summary>
        /// 动态属性14
        /// </summary>
        DynamicAttr14 = 66,
        /// <summary>
        /// 动态属性15
        /// </summary>
        DynamicAttr15 = 67,
        /// <summary>
        /// 动态属性16
        /// </summary>
        DynamicAttr16 = 68,
        /// <summary>
        /// 动态属性17
        /// </summary>
        DynamicAttr17 = 69,
        /// <summary>
        /// 动态属性18
        /// </summary>
        DynamicAttr18 = 70,
        /// <summary>
        /// 动态属性19
        /// </summary>
        DynamicAttr19 = 71,
        /// <summary>
        /// 动态属性20
        /// </summary>
        DynamicAttr20 = 72,
        /// <summary>
        /// 当前血量
        /// </summary>
        CurHp = 73,
        /// <summary>
        /// Meta无
        /// </summary>
        MetaAttrNone = 74,
        /// <summary>
        /// 伤害
        /// </summary>
        MetaAttrDamage = 75,
        Max = 76,
    }

} 

