
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.battle
{ 
    /// <summary>
    /// 技能类型
    /// </summary>
    public enum EGameSkillType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 普通攻击
        /// </summary>
        Attack = 1,
        /// <summary>
        /// 被动技能
        /// </summary>
        Passive = 2,
        /// <summary>
        /// 常规技能
        /// </summary>
        Normal = 3,
        /// <summary>
        /// 身法技能
        /// </summary>
        Move = 4,
        /// <summary>
        /// 心法技能
        /// </summary>
        Heart = 5,
    }

} 

