
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.battle
{ 
    public enum EGameAttr
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 最大血量
        /// </summary>
        MaxHp = 1,
        /// <summary>
        /// 最大血量Base
        /// </summary>
        MaxHpBase = 2,
        /// <summary>
        /// 最大血量Mult
        /// </summary>
        MaxHpMult = 3,
        /// <summary>
        /// 最大血量Add
        /// </summary>
        MaxHpAdd = 4,
        /// <summary>
        /// 攻击力
        /// </summary>
        Atk = 5,
        /// <summary>
        /// 攻击力Base
        /// </summary>
        AtkBase = 6,
        /// <summary>
        /// 攻击力Mult
        /// </summary>
        AtkMult = 7,
        /// <summary>
        /// 攻击力Add
        /// </summary>
        AtkAdd = 8,
        /// <summary>
        /// 暴击率
        /// </summary>
        CriticalRate = 9,
        /// <summary>
        /// 暴击率Base
        /// </summary>
        CriticalRateBase = 10,
        /// <summary>
        /// 暴击率Mult
        /// </summary>
        CriticalRateMult = 11,
        /// <summary>
        /// 暴击率Add
        /// </summary>
        CriticalRateAdd = 12,
        /// <summary>
        /// 抗暴击率
        /// </summary>
        DeCriticalRate = 13,
        /// <summary>
        /// 抗暴击率Base
        /// </summary>
        DeCriticalRateBase = 14,
        /// <summary>
        /// 抗暴击率Mult
        /// </summary>
        DeCriticalRateMult = 15,
        /// <summary>
        /// 抗暴击率Add
        /// </summary>
        DeCriticalRateAdd = 16,
        /// <summary>
        /// 暴击倍率
        /// </summary>
        CriticalRatio = 17,
        /// <summary>
        /// 暴击倍率Base
        /// </summary>
        CriticalRatioBase = 18,
        /// <summary>
        /// 暴击倍率Mult
        /// </summary>
        CriticalRatioMult = 19,
        /// <summary>
        /// 暴击倍率Add
        /// </summary>
        CriticalRatioAdd = 20,
        /// <summary>
        /// 抗暴击倍率
        /// </summary>
        DeCriticalRatio = 21,
        /// <summary>
        /// 抗暴击倍率Base
        /// </summary>
        DeCriticalRatioBase = 22,
        /// <summary>
        /// 抗暴击倍率Mult
        /// </summary>
        DeCriticalRatioMult = 23,
        /// <summary>
        /// 抗暴击倍率Add
        /// </summary>
        DeCriticalRatioAdd = 24,
        /// <summary>
        /// 总增伤
        /// </summary>
        DamageMore = 25,
        /// <summary>
        /// 总增Base
        /// </summary>
        DamageMoreBase = 26,
        /// <summary>
        /// 总增Mult
        /// </summary>
        DamageMoreMult = 27,
        /// <summary>
        /// 总增Add
        /// </summary>
        DamageMoreAdd = 28,
        /// <summary>
        /// 总减伤
        /// </summary>
        DamageLess = 29,
        /// <summary>
        /// 总减伤Base
        /// </summary>
        DamageLessBase = 30,
        /// <summary>
        /// 总减伤Mult
        /// </summary>
        DamageLessMult = 31,
        /// <summary>
        /// 总减伤Add
        /// </summary>
        DamageLessAdd = 32,
        /// <summary>
        /// 技能极速
        /// </summary>
        SkillHaste = 33,
        /// <summary>
        /// 技能极速Base
        /// </summary>
        SkillHasteBase = 34,
        /// <summary>
        /// 技能极速Mult
        /// </summary>
        SkillHasteMult = 35,
        /// <summary>
        /// 技能极速Add
        /// </summary>
        SkillHasteAdd = 36,
        /// <summary>
        /// 充能
        /// </summary>
        SpecialCharge = 37,
        /// <summary>
        /// 充能Base
        /// </summary>
        SpecialChargeBase = 38,
        /// <summary>
        /// 充能Mult
        /// </summary>
        SpecialChargeMult = 39,
        /// <summary>
        /// 充能Add
        /// </summary>
        SpecialChargeAdd = 40,
        /// <summary>
        /// 当前血量
        /// </summary>
        CurHp = 41,
        /// <summary>
        /// 当前能量
        /// </summary>
        CurSpecialEnergy = 42,
        Max = 43,
        /// <summary>
        /// Meta伤害
        /// </summary>
        MetaDamage = 44,
    }

} 

