
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
public sealed partial class EnityInitRow : Luban.BeanBase
{
    public EnityInitRow(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); InitSkills = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); InitSkills.Add(_e0);}}
        {int n0 = _buf.ReadSize(); InitAttrs = new System.Collections.Generic.Dictionary<battle.EGameAttr, float>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { battle.EGameAttr _k0;  _k0 = (battle.EGameAttr)_buf.ReadInt(); float _v0;  _v0 = _buf.ReadFloat();     InitAttrs.Add(_k0, _v0);}}
    }

    public static EnityInitRow DeserializeEnityInitRow(ByteBuf _buf)
    {
        return new battle.EnityInitRow(_buf);
    }

    public readonly int Id;
    public readonly System.Collections.Generic.List<int> InitSkills;
    public readonly System.Collections.Generic.Dictionary<battle.EGameAttr, float> InitAttrs;
   
    public const int __ID__ = 960342299;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "initSkills:" + Luban.StringUtil.CollectionToString(InitSkills) + ","
        + "initAttrs:" + Luban.StringUtil.CollectionToString(InitAttrs) + ","
        + "}";
    }
}
}

