
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.battle
{ 
    /// <summary>
    /// 技能属性
    /// </summary>
    public enum ESkillAttr
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 固定冷却缩减
        /// </summary>
        ReduceCdFixed = 1,
        /// <summary>
        /// 百分比冷却缩减
        /// </summary>
        ReduceCdPct = 2,
        /// <summary>
        /// 动态属性1
        /// </summary>
        Dynamic1 = 3,
        /// <summary>
        /// 动态属性2
        /// </summary>
        Dynamic2 = 4,
        /// <summary>
        /// 动态属性3
        /// </summary>
        Dynamic3 = 5,
        /// <summary>
        /// 动态属性4
        /// </summary>
        Dynamic4 = 6,
        /// <summary>
        /// 动态属性5
        /// </summary>
        Dynamic5 = 7,
        /// <summary>
        /// 动态属性6
        /// </summary>
        Dynamic6 = 8,
        /// <summary>
        /// 动态属性7
        /// </summary>
        Dynamic7 = 9,
        /// <summary>
        /// 动态属性8
        /// </summary>
        Dynamic8 = 10,
        /// <summary>
        /// 动态属性9
        /// </summary>
        Dynamic9 = 11,
        Max = 12,
    }

} 

