
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.battle
{ 
    /// <summary>
    /// 堆叠类型
    /// </summary>
    public enum EStackType
    {
        /// <summary>
        /// 不堆叠
        /// </summary>
        None = 0,
        /// <summary>
        /// 按来源
        /// </summary>
        Source = 1,
        /// <summary>
        /// 按目标
        /// </summary>
        Target = 2,
    }

} 

