
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.battle
{ 
    /// <summary>
    /// 堆叠失效类型
    /// </summary>
    public enum EStackExpireType
    {
        /// <summary>
        /// 删除全部
        /// </summary>
        RemoveAll = 0,
        /// <summary>
        /// 删除单层
        /// </summary>
        RemoveOne = 1,
    }

} 

