
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
/// <summary>
/// 简单浮点计算器
/// </summary>
public sealed partial class FloatCalculator : BaseCalculator
{
    public FloatCalculator(ByteBuf _buf)  : base(_buf) 
    {
        Value = _buf.ReadFloat();
        MultStackCount = _buf.ReadBool();
    }

    public static FloatCalculator DeserializeFloatCalculator(ByteBuf _buf)
    {
        return new battle.FloatCalculator(_buf);
    }

    /// <summary>
    /// 数值，需要指定
    /// </summary>
    public readonly float Value;
    /// <summary>
    /// 乘以层数，默认FALSE
    /// </summary>
    public readonly bool MultStackCount;
   
    public const int __ID__ = -1883529944;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "value:" + Value + ","
        + "multStackCount:" + MultStackCount + ","
        + "}";
    }
}
}

