
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
/// <summary>
/// 技能
/// </summary>
public sealed partial class GameSkillRow : Luban.BeanBase
{
    public GameSkillRow(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Desc = _buf.ReadString();
        Type = (battle.EGameSkillType)_buf.ReadInt();
        Cd = _buf.ReadFloat();
        Duration = _buf.ReadFloat();
        {int n0 = _buf.ReadSize(); ToTargetEffectTimeline = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); ToTargetEffectTimeline.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ToTargetEffect = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ToTargetEffect.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ToSelfEffectTimeline = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); ToSelfEffectTimeline.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ToSelfEffect = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ToSelfEffect.Add(_e0);}}
    }

    public static GameSkillRow DeserializeGameSkillRow(ByteBuf _buf)
    {
        return new battle.GameSkillRow(_buf);
    }

    /// <summary>
    /// 需要指定，必须与文件名序号一致
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述。需要指定
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 技能类型。需要指定
    /// </summary>
    public readonly battle.EGameSkillType Type;
    /// <summary>
    /// 冷却时间。需要指定
    /// </summary>
    public readonly float Cd;
    /// <summary>
    /// 技能时长
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// 对目标效果的时间轴。最大值不可超过技能时长。默认为空
    /// </summary>
    public readonly System.Collections.Generic.List<float> ToTargetEffectTimeline;
    /// <summary>
    /// 对目标效果。和时间轴一一对应且在相应的时间触发效果。默认为空
    /// </summary>
    public readonly System.Collections.Generic.List<int> ToTargetEffect;
    public System.Collections.Generic.List<battle.GameEffectRow> ToTargetEffect_Ref;
    /// <summary>
    /// 对自身效果的时间轴。最大值不可超过技能时长。默认为空
    /// </summary>
    public readonly System.Collections.Generic.List<float> ToSelfEffectTimeline;
    /// <summary>
    /// 对自身效果。和时间轴一一对应且在相应的时间触发效果。默认为空
    /// </summary>
    public readonly System.Collections.Generic.List<int> ToSelfEffect;
    public System.Collections.Generic.List<battle.GameEffectRow> ToSelfEffect_Ref;
   
    public const int __ID__ = 1827455345;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        ToTargetEffect_Ref = new System.Collections.Generic.List<battle.GameEffectRow>();
        foreach (var _v in ToTargetEffect) { ToTargetEffect_Ref.Add(tables.GameEffectTable.GetOrDefault(_v)); }

        ToSelfEffect_Ref = new System.Collections.Generic.List<battle.GameEffectRow>();
        foreach (var _v in ToSelfEffect) { ToSelfEffect_Ref.Add(tables.GameEffectTable.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "type:" + Type + ","
        + "cd:" + Cd + ","
        + "duration:" + Duration + ","
        + "toTargetEffectTimeline:" + Luban.StringUtil.CollectionToString(ToTargetEffectTimeline) + ","
        + "toTargetEffect:" + Luban.StringUtil.CollectionToString(ToTargetEffect) + ","
        + "toSelfEffectTimeline:" + Luban.StringUtil.CollectionToString(ToSelfEffectTimeline) + ","
        + "toSelfEffect:" + Luban.StringUtil.CollectionToString(ToSelfEffect) + ","
        + "}";
    }
}
}

