
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
/// <summary>
/// 肉鸽词条
/// </summary>
public sealed partial class GameRougeEffectRow : Luban.BeanBase
{
    public GameRougeEffectRow(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Desc = _buf.ReadString();
        Quality = (battle.EGameRougeEffectQuality)_buf.ReadInt();
        CountLimit = _buf.ReadInt();
        NeedRougeEffect = _buf.ReadInt();
        NeedRougeEffect_Ref = null;
        NoRougeEffect = _buf.ReadInt();
        NoRougeEffect_Ref = null;
        {int n0 = _buf.ReadSize(); GameEffects = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); GameEffects.Add(_e0);}}
    }

    public static GameRougeEffectRow DeserializeGameRougeEffectRow(ByteBuf _buf)
    {
        return new battle.GameRougeEffectRow(_buf);
    }

    /// <summary>
    /// 默认与文件名序号一致，由你自动填充，禁止用户主动修改
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述。需要指定
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 词条品质。需要指定
    /// </summary>
    public readonly battle.EGameRougeEffectQuality Quality;
    /// <summary>
    /// 可以选择的次数。需要指定
    /// </summary>
    public readonly int CountLimit;
    /// <summary>
    /// 前置词条要求，默认为空
    /// </summary>
    public readonly int NeedRougeEffect;
    public battle.GameRougeEffectRow NeedRougeEffect_Ref;
    /// <summary>
    /// 互斥词条要求，默认为空
    /// </summary>
    public readonly int NoRougeEffect;
    public battle.GameRougeEffectRow NoRougeEffect_Ref;
    /// <summary>
    /// 该词条触发的效果。默认为空
    /// </summary>
    public readonly System.Collections.Generic.List<int> GameEffects;
    public System.Collections.Generic.List<battle.GameEffectRow> GameEffects_Ref;
   
    public const int __ID__ = -1768617957;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        NeedRougeEffect_Ref = tables.GameRougeEffectTable.GetOrDefault(NeedRougeEffect);
        NoRougeEffect_Ref = tables.GameRougeEffectTable.GetOrDefault(NoRougeEffect);
        GameEffects_Ref = new System.Collections.Generic.List<battle.GameEffectRow>();
        foreach (var _v in GameEffects) { GameEffects_Ref.Add(tables.GameEffectTable.GetOrDefault(_v)); }

    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "quality:" + Quality + ","
        + "countLimit:" + CountLimit + ","
        + "needRougeEffect:" + NeedRougeEffect + ","
        + "noRougeEffect:" + NoRougeEffect + ","
        + "gameEffects:" + Luban.StringUtil.CollectionToString(GameEffects) + ","
        + "}";
    }
}
}

