
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
/// <summary>
/// 游戏效果
/// </summary>
public sealed partial class GameEffectRow : Luban.BeanBase
{
    public GameEffectRow(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Desc = _buf.ReadString();
        DurationType = (battle.EDurationType)_buf.ReadInt();
        DurationTime = _buf.ReadFloat();
        {int n0 = _buf.ReadSize(); GrantedTags = new System.Collections.Generic.List<battle.EGameTag>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { battle.EGameTag _e0;  _e0 = (battle.EGameTag)_buf.ReadInt(); GrantedTags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ApplyRequiredTags = new System.Collections.Generic.List<battle.EGameTag>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { battle.EGameTag _e0;  _e0 = (battle.EGameTag)_buf.ReadInt(); ApplyRequiredTags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); OnGoingRequiredTags = new System.Collections.Generic.List<battle.EGameTag>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { battle.EGameTag _e0;  _e0 = (battle.EGameTag)_buf.ReadInt(); OnGoingRequiredTags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ImmuneWhenTags = new System.Collections.Generic.List<battle.EGameTag>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { battle.EGameTag _e0;  _e0 = (battle.EGameTag)_buf.ReadInt(); ImmuneWhenTags.Add(_e0);}}
        PeriodDuration = _buf.ReadFloat();
        FirstPeriodImmediately = _buf.ReadBool();
        {int n0 = _buf.ReadSize(); PeriodEffect = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); PeriodEffect.Add(_e0);}}
        StackType = (battle.EStackType)_buf.ReadInt();
        StackCountLimit = _buf.ReadInt();
        OverflowStackRefreshDuration = _buf.ReadBool();
        StackExpireType = (battle.EStackExpireType)_buf.ReadInt();
        {int n0 = _buf.ReadSize(); AttrModifiers = new System.Collections.Generic.List<battle.GameAttrModifier>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { battle.GameAttrModifier _e0;  _e0 = global::cfg.battle.GameAttrModifier.DeserializeGameAttrModifier(_buf); AttrModifiers.Add(_e0);}}
        BindCodeLogic = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); DynamicParams = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); DynamicParams.Add(_e0);}}
    }

    public static GameEffectRow DeserializeGameEffectRow(ByteBuf _buf)
    {
        return new battle.GameEffectRow(_buf);
    }

    /// <summary>
    /// 不需要也禁止用户输入。默认等于文件名序号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 持续时间类型。默认 即时
    /// </summary>
    public readonly battle.EDurationType DurationType;
    /// <summary>
    /// 持续时间。非即时效果时才需要用户指定。否则默认0
    /// </summary>
    public readonly float DurationTime;
    /// <summary>
    /// 附加的标签。永久GE才可以添加。默认为空
    /// </summary>
    public readonly System.Collections.Generic.List<battle.EGameTag> GrantedTags;
    /// <summary>
    /// 添加所需要的标签。没有这些标签时效果不会被添加。默认为空
    /// </summary>
    public readonly System.Collections.Generic.List<battle.EGameTag> ApplyRequiredTags;
    /// <summary>
    /// 激活所需要的标签。没有这些标签时效果会被暂时移除。非即时效果才可以填写。默认为空
    /// </summary>
    public readonly System.Collections.Generic.List<battle.EGameTag> OnGoingRequiredTags;
    /// <summary>
    /// 拥有这些标签时免疫该效果。默认为空
    /// </summary>
    public readonly System.Collections.Generic.List<battle.EGameTag> ImmuneWhenTags;
    /// <summary>
    /// 周期时间 &gt;0 时代表存在周期效果。非即时效果时才可以填写。最小是0.1。并且必须要有periodEffect。默认为0
    /// </summary>
    public readonly float PeriodDuration;
    /// <summary>
    /// 立刻触发第一次周期效果。存在周期时间时才可以修改。默认为FALSE
    /// </summary>
    public readonly bool FirstPeriodImmediately;
    /// <summary>
    /// 触发的周期效果。周期效果必须是即时效果。引用GameEffectTable且禁止引用自身。当存在周期时间&gt;0时必须指定。否则为空
    /// </summary>
    public readonly System.Collections.Generic.List<int> PeriodEffect;
    public System.Collections.Generic.List<battle.GameEffectRow> PeriodEffect_Ref;
    /// <summary>
    /// 堆叠类型。非即时效果才可以填写。否则默认为 不堆叠
    /// </summary>
    public readonly battle.EStackType StackType;
    /// <summary>
    /// 堆叠数量限制。堆叠类型非0才可以指定。默认为1
    /// </summary>
    public readonly int StackCountLimit;
    /// <summary>
    /// 添加层数时如果溢出是否刷新持续时间。堆叠类型非0才可以指定。默认为TRUE
    /// </summary>
    public readonly bool OverflowStackRefreshDuration;
    /// <summary>
    /// 层数失效类型。堆叠类型非0时才可以指定。默认为 删除全部
    /// </summary>
    public readonly battle.EStackExpireType StackExpireType;
    /// <summary>
    /// 属性修改。默认为空
    /// </summary>
    public readonly System.Collections.Generic.List<battle.GameAttrModifier> AttrModifiers;
    /// <summary>
    /// 存在代码逻辑。如果不为0。说明这个BUFF有对应值的自定义逻辑存在。非即时BUFF才可以添加自定义逻辑。默认0
    /// </summary>
    public readonly int BindCodeLogic;
    /// <summary>
    /// 自由参数。默认空
    /// </summary>
    public readonly System.Collections.Generic.List<float> DynamicParams;
   
    public const int __ID__ = 1651707873;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PeriodEffect_Ref = new System.Collections.Generic.List<battle.GameEffectRow>();
        foreach (var _v in PeriodEffect) { PeriodEffect_Ref.Add(tables.GameEffectTable.GetOrDefault(_v)); }

        foreach (var _e in AttrModifiers) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "durationType:" + DurationType + ","
        + "durationTime:" + DurationTime + ","
        + "grantedTags:" + Luban.StringUtil.CollectionToString(GrantedTags) + ","
        + "applyRequiredTags:" + Luban.StringUtil.CollectionToString(ApplyRequiredTags) + ","
        + "onGoingRequiredTags:" + Luban.StringUtil.CollectionToString(OnGoingRequiredTags) + ","
        + "immuneWhenTags:" + Luban.StringUtil.CollectionToString(ImmuneWhenTags) + ","
        + "periodDuration:" + PeriodDuration + ","
        + "firstPeriodImmediately:" + FirstPeriodImmediately + ","
        + "periodEffect:" + Luban.StringUtil.CollectionToString(PeriodEffect) + ","
        + "stackType:" + StackType + ","
        + "stackCountLimit:" + StackCountLimit + ","
        + "overflowStackRefreshDuration:" + OverflowStackRefreshDuration + ","
        + "stackExpireType:" + StackExpireType + ","
        + "attrModifiers:" + Luban.StringUtil.CollectionToString(AttrModifiers) + ","
        + "bindCodeLogic:" + BindCodeLogic + ","
        + "dynamicParams:" + Luban.StringUtil.CollectionToString(DynamicParams) + ","
        + "}";
    }
}
}

