
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
public partial class GameAttrInitTable
{
    private readonly System.Collections.Generic.Dictionary<int, battle.GameAttrInitRow> _dataMap;
    private readonly System.Collections.Generic.List<battle.GameAttrInitRow> _dataList;
    
    public GameAttrInitTable(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.GameAttrInitRow>(n);
        _dataList = new System.Collections.Generic.List<battle.GameAttrInitRow>(n);
        for(int i = n ; i > 0 ; --i)
        {
            battle.GameAttrInitRow _v;
            _v = global::cfg.battle.GameAttrInitRow.DeserializeGameAttrInitRow(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, battle.GameAttrInitRow> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<battle.GameAttrInitRow> DataList => _dataList;

    public battle.GameAttrInitRow GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public battle.GameAttrInitRow Get(int key) => _dataMap[key];
    public battle.GameAttrInitRow this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

