
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
public sealed partial class GameAttrInitRow : Luban.BeanBase
{
    public GameAttrInitRow(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); InitValues = new System.Collections.Generic.Dictionary<battle.EGameAttr, float>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { battle.EGameAttr _k0;  _k0 = (battle.EGameAttr)_buf.ReadInt(); float _v0;  _v0 = _buf.ReadFloat();     InitValues.Add(_k0, _v0);}}
    }

    public static GameAttrInitRow DeserializeGameAttrInitRow(ByteBuf _buf)
    {
        return new battle.GameAttrInitRow(_buf);
    }

    public readonly int Id;
    public readonly System.Collections.Generic.Dictionary<battle.EGameAttr, float> InitValues;
   
    public const int __ID__ = -1808521519;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "initValues:" + Luban.StringUtil.CollectionToString(InitValues) + ","
        + "}";
    }
}
}

