
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
public partial class GlobalBattleTable
{

     private readonly battle.GlobalBattleRow _data;

     public battle.GlobalBattleRow Data => _data;

    public GlobalBattleTable(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::cfg.battle.GlobalBattleRow.DeserializeGlobalBattleRow(_buf);
    }


    /// <summary>
    /// 肉鸽词条品质权重，越高越容易抽到
    /// </summary>
     public System.Collections.Generic.Dictionary<battle.EGameRougeEffectQuality, int> RougeEffectQualityPriority => _data.RougeEffectQualityPriority;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

