
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
public sealed partial class GlobalBattleRow : Luban.BeanBase
{
    public GlobalBattleRow(ByteBuf _buf) 
    {
        {int n0 = _buf.ReadSize(); RougeEffectQualityPriority = new System.Collections.Generic.Dictionary<battle.EGameRougeEffectQuality, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { battle.EGameRougeEffectQuality _k0;  _k0 = (battle.EGameRougeEffectQuality)_buf.ReadInt(); int _v0;  _v0 = _buf.ReadInt();     RougeEffectQualityPriority.Add(_k0, _v0);}}
    }

    public static GlobalBattleRow DeserializeGlobalBattleRow(ByteBuf _buf)
    {
        return new battle.GlobalBattleRow(_buf);
    }

    /// <summary>
    /// 肉鸽词条品质权重，越高越容易抽到
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<battle.EGameRougeEffectQuality, int> RougeEffectQualityPriority;
   
    public const int __ID__ = 447909961;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "rougeEffectQualityPriority:" + Luban.StringUtil.CollectionToString(RougeEffectQualityPriority) + ","
        + "}";
    }
}
}

