
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.battle
{
/// <summary>
/// 修改技能属性
/// </summary>
public sealed partial class MetaChangeSkillAttrCalculator : BaseCalculator
{
    public MetaChangeSkillAttrCalculator(ByteBuf _buf)  : base(_buf) 
    {
        SkillId = _buf.ReadInt();
        SkillId_Ref = null;
        AttrId = (battle.ESkillAttr)_buf.ReadInt();
        Value = _buf.ReadFloat();
    }

    public static MetaChangeSkillAttrCalculator DeserializeMetaChangeSkillAttrCalculator(ByteBuf _buf)
    {
        return new battle.MetaChangeSkillAttrCalculator(_buf);
    }

    /// <summary>
    /// 目标技能，需要指定
    /// </summary>
    public readonly int SkillId;
    public battle.GameSkillRow SkillId_Ref;
    /// <summary>
    /// 属性类型，需要指定
    /// </summary>
    public readonly battle.ESkillAttr AttrId;
    /// <summary>
    /// 修改值，需要指定
    /// </summary>
    public readonly float Value;
   
    public const int __ID__ = -534036135;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        SkillId_Ref = tables.GameSkillTable.GetOrDefault(SkillId);
    }

    public override string ToString()
    {
        return "{ "
        + "skillId:" + SkillId + ","
        + "attrId:" + AttrId + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

