
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public battle.GameEffectTable GameEffectTable {get; }
    public battle.GameRougeEffectTable GameRougeEffectTable {get; }
    public battle.GameSkillTable GameSkillTable {get; }
    public battle.GlobalBattleTable GlobalBattleTable {get; }
    public battle.EnityInitTable EnityInitTable {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        GameEffectTable = new battle.GameEffectTable(loader("battle_gameeffecttable"));
        GameRougeEffectTable = new battle.GameRougeEffectTable(loader("battle_gamerougeeffecttable"));
        GameSkillTable = new battle.GameSkillTable(loader("battle_gameskilltable"));
        GlobalBattleTable = new battle.GlobalBattleTable(loader("battle_globalbattletable"));
        EnityInitTable = new battle.EnityInitTable(loader("battle_enityinittable"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GameEffectTable.ResolveRef(this);
        GameRougeEffectTable.ResolveRef(this);
        GameSkillTable.ResolveRef(this);
        GlobalBattleTable.ResolveRef(this);
        EnityInitTable.ResolveRef(this);
    }
}

}
