
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public battle.GameAttrInitTable GameAttrInitTable {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        GameAttrInitTable = new battle.GameAttrInitTable(loader("battle_gameattrinittable"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GameAttrInitTable.ResolveRef(this);
    }
}

}
