
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public battle.GameAttrInitTable GameAttrInitTable {get; }
    public battle.GameEffectTable GameEffectTable {get; }
    public battle.GameRougeEffectTable GameRougeEffectTable {get; }
    public battle.GameSkillTable GameSkillTable {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        GameAttrInitTable = new battle.GameAttrInitTable(loader("battle_gameattrinittable"));
        GameEffectTable = new battle.GameEffectTable(loader("battle_gameeffecttable"));
        GameRougeEffectTable = new battle.GameRougeEffectTable(loader("battle_gamerougeeffecttable"));
        GameSkillTable = new battle.GameSkillTable(loader("battle_gameskilltable"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GameAttrInitTable.ResolveRef(this);
        GameEffectTable.ResolveRef(this);
        GameRougeEffectTable.ResolveRef(this);
        GameSkillTable.ResolveRef(this);
    }
}

}
