
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.battle
{
/// <summary>
/// 数值计算器 基类
/// </summary>
public abstract partial class BaseCalculator : Luban.BeanBase
{
    public BaseCalculator(JSONNode _buf) 
    {
    }

    public static BaseCalculator DeserializeBaseCalculator(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "FloatCalculator": return new battle.FloatCalculator(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

