
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.battle
{
/// <summary>
/// 简单浮点计算器
/// </summary>
public sealed partial class FloatCalculator : BaseCalculator
{
    public FloatCalculator(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["value"].IsObject) { throw new SerializationException(); }  Value = global::cfg.battle.DynamicValue.DeserializeDynamicValue(_buf["value"]);  }
    }

    public static FloatCalculator DeserializeFloatCalculator(JSONNode _buf)
    {
        return new battle.FloatCalculator(_buf);
    }

    /// <summary>
    /// 数值，需要指定
    /// </summary>
    public readonly battle.DynamicValue Value;
   
    public const int __ID__ = -1883529944;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Value?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "value:" + Value + ","
        + "}";
    }
}
}

