
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.battle
{
/// <summary>
/// 属性修改器
/// </summary>
public sealed partial class GameAttrModifier : Luban.BeanBase
{
    public GameAttrModifier(JSONNode _buf) 
    {
        { if(!_buf["attr"].IsNumber) { throw new SerializationException(); }  Attr = (battle.EGameAttr)_buf["attr"].AsInt; }
        { if(!_buf["calculator"].IsObject) { throw new SerializationException(); }  Calculator = global::cfg.battle.BaseCalculator.DeserializeBaseCalculator(_buf["calculator"]);  }
    }

    public static GameAttrModifier DeserializeGameAttrModifier(JSONNode _buf)
    {
        return new battle.GameAttrModifier(_buf);
    }

    /// <summary>
    /// 属性类型，需要指定
    /// </summary>
    public readonly battle.EGameAttr Attr;
    /// <summary>
    /// 数值计算器，代表修改的值，需要指定
    /// </summary>
    public readonly battle.BaseCalculator Calculator;
   
    public const int __ID__ = -1113496688;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Calculator?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "attr:" + Attr + ","
        + "calculator:" + Calculator + ","
        + "}";
    }
}
}

