
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.battle
{
public sealed partial class GameAttrInitRow : Luban.BeanBase
{
    public GameAttrInitRow(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["initValues"]; if(!__json0.IsArray) { throw new SerializationException(); } InitValues = new System.Collections.Generic.Dictionary<battle.EGameAttr, float>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { battle.EGameAttr _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = (battle.EGameAttr)__e0[0].AsInt; } float _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  InitValues.Add(_k0, _v0); }   }
    }

    public static GameAttrInitRow DeserializeGameAttrInitRow(JSONNode _buf)
    {
        return new battle.GameAttrInitRow(_buf);
    }

    public readonly int Id;
    public readonly System.Collections.Generic.Dictionary<battle.EGameAttr, float> InitValues;
   
    public const int __ID__ = -1808521519;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "initValues:" + Luban.StringUtil.CollectionToString(InitValues) + ","
        + "}";
    }
}
}

